# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_auto_20160511_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingitem',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
