# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('exchanged', models.BooleanField(default=False)),
                ('remark', models.TextField()),
                ('issued', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=200)),
                ('bank_branch', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
