# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cheque', '0002_cheque_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='brought_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
