# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_auto_20160516_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 18, 19, 17, 502000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='created_at',
            field=models.DateField(editable=False),
        ),
    ]
