# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_auto_20160601_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 6, 1, 18, 26, 38, 788000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 18, 26, 29, 59000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 18, 26, 29, 61000, tzinfo=utc)),
        ),
    ]
