# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_auto_20160601_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 18, 32, 36, 136000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='created_at',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 18, 32, 36, 138000, tzinfo=utc)),
        ),
    ]
